on: push

name: pipeline

jobs:
  changedFiles:
    name: y2_devops_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        tags: ${{ secrets.DOCKER_USER }}/yad2_devops
        tag_with_sha: true
