on: push

name: pipeline

jobs:
  changedFiles:
    name: y2_devops_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: pipeline
      uses: ./.github/actions/pipeline
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}


